<?php

namespace Database\Seeders;

use App\Models\Department;
use App\Models\Voucher;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Nette\Utils\Random;

class DepartmentsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Department::factory()->create([
            'title_ar' => 'مخازن سوبر ماركت',
            'title_en' => 'Mkhazin Super Market',
            'description_ar' => 'شركة مخازن المملكة العالمية تعد من الشركات الرائدة في مجال بيع المنتجات عبر السوبر ماركت، حيث تقدم للعملاء تجربة تسوق متكاملة ومريحة. تتميز محلات السوبر ماركت التابعة لها بتنوع منتجاتها التي تشمل المواد الغذائية الطازجة والمعلبة، الخضروات والفواكه، اللحوم والأسماك، وكذلك المواد المنزلية، التنظيف، العناية الشخصية. تلتزم الشركة بتقديم أعلى مستويات الجودة والأسعار التنافسية، مما يجعلها وجهة مفضلة للعملاء الذين يبحثون عن الراحة والجودة. بالإضافة إلى ذلك، تسعى الشركة لتوفير بيئة تسوق مريحة عبر تصميم المتاجر بطريقة عملية، مع توفير مساحات واسعة للتجول والاختيار بسهولة.كما أن مخازن المملكة العالمية تهتم بتقديم خدمة العملاء على أعلى مستوى، حيث يتم تدريب الموظفين على تقديم المساعدة والتوجيه للعملاء في كل مرة يتسوقون فيها. تسعى الشركة للحفاظ على توفير المنتجات بشكل دائم لتلبية احتياجات المستهلكين اليومية، مما يضمن توافر السلع بشكل مستمر. وتحافظ الشركة على سمعتها الطيبة من خلال التزامها بتقديم العروض الترويجية والخصومات المميزة التي تعزز تجربة التسوق وتجعله أكثر متعة وفائدة لجميع العملاء.',
            'description_en' => 'Makhazin Al-Mamlaka Al-Alamia is a leading company in the retail sector, specializing in supermarkets that offer a comprehensive and convenient shopping experience. The supermarkets under its management provide a wide range of products, including fresh and packaged food items, vegetables and fruits, meats and seafood, as well as household products, cleaning supplies, and personal care. The company is committed to offering high-quality products at competitive prices, making it a preferred destination for customers seeking convenience and quality. In addition, Makhazin Al-Mamlaka Al-Alamia focuses on providing a comfortable shopping environment by designing stores that are spacious and easy to navigate. Customer service is a top priority at Makhazin Al-Mamlaka Al-Alamia, with staff trained to assist and guide shoppers every time they visit. The company strives to maintain consistent availability of products to meet daily consumer needs, ensuring that shelves are always stocked. Makhazin Al-Mamlaka Al-Alamia also offers regular promotions and discounts, which enhance the shopping experience and provide customers with more value for their money. With its commitment to customer satisfaction and quality, the company continues to maintain a strong reputation in the retail sector.',
            'key' => 'super',
            'tags_ar' => ['سوبر ماركت', 'تسوق', 'منتجات غذائية', 'منتجات منزلية', 'مواد غذائية', 'خضروات', 'فواكه', 'لحوم', 'أسماك', 'مواد تنظيف', 'مستلزمات منزلية', 'عناية شخصية', 'أدوية', 'منتجات عضوية', 'تسوق يومي', 'عروض', 'خصومات', 'تسوق عبر الإنترنت', 'منتجات طبيعية', 'سوبر ماركت محلي', 'سوبر ماركت في منطقتك', 'تجربة تسوق', 'أسعار تنافسية', 'جودة عالية', 'خدمة العملاء', 'منتجات صحية', 'طعام طازج', 'التسوق بأسعار معقولة', 'منتجات متنوعة', 'مستلزمات الأطفال', 'منتجات بيئية', 'تسوق مريح', 'متجر متعدد الأقسام', 'خدمة توصيل', 'تسوق سهل', 'تسوق عائلي', 'جودة المنتجات', 'عروض ترويجية', 'متجر قريب منك', 'شراء سهل', 'تسوق متنوع', 'سوبر ماركت بأسعار مخفضة', 'تسوق مبتكر', 'تجربة تسوق مريحة', 'جودة المنتجات', 'طلبات تسوق', 'اختيارات واسعة', 'مستلزمات منزلية فاخرة', 'شراء يومي', 'متجر موثوق'],
            'tags_en' => ['supermarket', 'shopping', 'grocery products', 'household products', 'food items', 'vegetables', 'fruits', 'meats', 'seafood', 'cleaning supplies', 'household essentials', 'personal care', 'pharmaceuticals', 'organic products', 'daily shopping', 'offers', 'discounts', 'online shopping', 'natural products', 'local supermarket', 'supermarket near you', 'shopping experience', 'competitive prices', 'high quality', 'customer service', 'healthy products', 'fresh food', 'affordable shopping', 'diverse products', 'baby products', 'eco-friendly products', 'convenient shopping', 'multi-department store', 'delivery service', 'easy shopping', 'family shopping', 'product quality', 'promotional offers', 'nearby store', 'easy purchase', 'varied shopping', 'discounted supermarket', 'innovative shopping', 'comfortable shopping experience', 'product requests', 'wide selection', 'luxury household products', 'daily shopping', 'reliable store'],
        ]);

        Department::factory()->create([
            'title_ar' => 'مخازن هايبر ماركت',
            'title_en' => 'Mkhazin Hyber Market',
            'description_ar' => 'شركة مخازن المملكة العالمية تمتلك سلسلة من الهايبر ماركت التي تعد من أكبر وأهم الوجهات التجارية في المنطقة. توفر هذه الهايبر ماركت تجربة تسوق شاملة لا مثيل لها، حيث تتضمن مجموعة واسعة من المنتجات التي تغطي كافة احتياجات الأسرة والشركات. تقدم الهايبر ماركت مجموعة متنوعة من المواد الغذائية الطازجة، مثل اللحوم والدواجن، الأسماك، الفواكه والخضروات الطازجة، بالإضافة إلى المنتجات المعلبة والمنتجات المجمدة. كما يمكن للعملاء العثور على كافة أنواع الأدوات المنزلية، الأجهزة الكهربائية، مستحضرات التجميل، والعناية بالبشرة، بالإضافة إلى مجموعة واسعة من المنتجات الصحية. تتميز الهايبر ماركت التي تديرها الشركة بأنها تشمل جميع الفئات السعرية وتلبي احتياجات جميع العملاء، من خلال تقديم منتجات ذات جودة عالية بأسعار تنافسية. كما تلتزم الشركة بتوفير بيئة تسوق مريحة باستخدام التصاميم الحديثة والتجهيزات المتطورة، ما يسهل على العملاء التنقل داخل المتاجر والعثور على ما يحتاجونه بسهولة. كما توفر الشركة العديد من العروض والتخفيضات المستمرة على المنتجات المختلفة، ما يجعلها الخيار الأول للعديد من العائلات والأفراد الذين يرغبون في الحصول على أفضل قيمة مقابل المال. تهدف الشركة إلى جعل تجربة التسوق في الهايبر ماركت تجربة مريحة وفعّالة، مع التركيز على التنوع الكبير في المنتجات وجودتها الممتازة.',
            'description_en' => 'Makhazin Al-Mamlaka Al-Alamia operates a chain of hypermarkets that are among the largest and most important retail destinations in the region. These hypermarkets offer an unparalleled shopping experience, featuring a broad range of products that meet the needs of families and businesses alike. Customers can find everything from fresh food items like meats, poultry, seafood, vegetables, and fruits to canned goods and frozen foods. Additionally, the hypermarkets carry a wide selection of household appliances, beauty products, and health care items. The hypermarkets managed by Makhazin Al-Mamlaka Al-Alamia cater to all customer needs by offering products across various price points, ensuring that everyone can find high-quality items at competitive prices. The stores are designed with modern layouts and advanced equipment, making it easier for customers to navigate and find what they need. Al-Mamlakah Stores also regularly offers promotions and discounts on various products, making it the go-to destination for many families and individuals looking for the best value for their money. The company’s goal is to provide an efficient, enjoyable, and rewarding shopping experience, with a focus on product variety and excellence.',
            'key' => 'hyper',
            'tags_ar' => ['هايبر ماركت', 'تسوق شامل', 'منتجات متنوعة', 'تسوق هائل', 'منتجات منزلية', 'ملابس', 'أحذية', 'أدوات منزلية', 'أجهزة كهربائية', 'سوبر ماركت كبير', 'مواد غذائية', 'تخفيضات', 'عروض خاصة', 'تسوق بأسعار منافسة', 'منتجات عالية الجودة', 'تسوق مريح', 'منتجات طبيعية', 'تسوق بتخفيضات', 'متجر متعدد الأقسام', 'تسوق عائلي', 'أسعار تنافسية', 'أسواق محلية', 'بيع بالجملة', 'مشتريات كبيرة', 'مستلزمات منزلية', 'شحن مجاني', 'جودة الخدمة', 'تسوق حديث', 'تسوق مريح', 'هايبر ماركت محلي', 'سوبر ماركت ضخم', 'طلبات بالجملة', 'ملابس وأزياء', 'أدوات كهربائية', 'أطعمة متنوعة', 'متاجر موسمية', 'تسوق ممتاز', 'تخفيضات كبيرة', 'عروض موسمية', 'تسوق غير محدود', 'تجارة الجملة', 'هايبر ماركت بأسعار مخفضة', 'متجر مفتوح', 'شراء متعدد', 'تسوق مميز', 'مستلزمات شتوية', 'تخفيضات مستمرة', 'متجر متكامل'],
            'tags_en' => ['hypermarket', 'comprehensive shopping', 'diverse products', 'massive shopping', 'household items', 'clothing', 'shoes', 'home appliances', 'large supermarket', 'grocery items', 'discounts', 'special offers', 'competitive shopping', 'high quality products', 'convenient shopping', 'natural products', 'discounted shopping', 'multi-department store', 'family shopping', 'competitive prices', 'local markets', 'wholesale shopping', 'bulk purchases', 'household essentials', 'free shipping', 'service quality', 'modern shopping', 'convenient shopping', 'local hypermarket', 'huge supermarket', 'wholesale orders', 'clothing and fashion', 'electrical appliances', 'variety of food', 'seasonal stores', 'excellent shopping', 'big discounts', 'seasonal offers', 'unlimited shopping', 'wholesale trade', 'discounted hypermarket', 'open store', 'multiple purchases', 'distinguished shopping', 'winter essentials', 'continuous discounts', 'complete store'],
        ]);

        Department::factory()->create([
            'title_ar' => 'مخازن الجملة',
            'title_en' => 'Mkhazin whole sale',
            'description_ar' => 'شركة مخازن المملكة العالمية تقدم خدمات البيع بالجملة التي تستهدف بشكل رئيسي الشركات والموزعين ومحلات البيع بالتجزئة، وكذلك المطاعم والفنادق. من خلال هذا النشاط، توفر الشركة للعملاء مجموعة واسعة من المنتجات بأسعار منخفضة تناسب احتياجات الأعمال التجارية التي تتطلب كميات كبيرة من السلع. تقدم الشركة خيارات متعددة من المنتجات التي تشمل المواد الغذائية والمشروبات، أدوات المنزل، منتجات التنظيف، والأجهزة الإلكترونية، وغيرها الكثير. يمكن للأعمال التجارية الحصول على هذه المنتجات بأسعار الجملة، مما يساعدهم على تقليل التكاليف وزيادة هوامش الربح. شركة مخازن المملكة العالمية تتميز بتقديم خدمات بيع بالجملة مرنة، حيث تقدم لعملائها إمكانية شراء كميات كبيرة من المنتجات بجودة ممتازة وبأسعار تنافسية. كما تسعى الشركة إلى بناء علاقات طويلة الأمد مع عملائها في القطاع التجاري، من خلال تقديم خدمات سريعة وموثوقة وتوريد مستمر للمنتجات. علاوة على ذلك، تحرص الشركة على تلبية احتياجات عملائها في الوقت المحدد مع توفير حلول مرنة للطلبات الخاصة. تعمل الشركة على ضمان أن جميع المنتجات التي توفرها للعملاء في قطاع البيع بالجملة تتمتع بأعلى معايير الجودة، مما يعزز من قدرة عملائها على تقديم خدمة متميزة لزبائنهم.',
            'description_en' => 'Makhazin Al-Mamlaka Al-Alamia also offers wholesale services, providing a wide variety of products at competitive prices aimed at businesses such as retailers, restaurants, hotels, and other commercial entities that need bulk purchases. Through this service, the company helps businesses access large quantities of products at discounted rates, allowing them to reduce their operational costs and improve their profit margins. The range of products available includes food and beverages, household items, cleaning products, electronic devices, and more. The company excels in offering flexible wholesale services, providing its customers with high-quality products at bulk prices. Makhazin Al-Mamlaka Al-Alamia builds long-term relationships with its wholesale clients by offering fast, reliable service and continuous product supply. The company also ensures that all wholesale products meet the highest standards of quality, which in turn helps clients deliver excellent service to their customers. Al-Mamlakah Stores is dedicated to providing flexible solutions for custom orders and ensuring timely deliveries to meet the unique needs of its wholesale clients.',
            'key' => 'wholesale',
            'tags_ar' => ['بيع بالجملة', 'منتجات بالجملة', 'تجارة الجملة', 'شراء بالجملة', 'أسعار منخفضة', 'تخفيضات بالجملة', 'أعمال تجارية', 'تجارة محلية', 'مشتريات بالجملة', 'توريد بالجملة', 'بيع منتجات بالجملة', 'مستلزمات مطاعم', 'موردين بالجملة', 'شراء بكميات كبيرة', 'منتجات بالجملة بأسعار تنافسية', 'بيع بالجملة للمتاجر', 'بيع بالجملة للمطاعم', 'بيع بالجملة للمنتجات الغذائية', 'بيع بالجملة للمستشفيات', 'موردين', 'بيع بالجملة للملابس', 'موردين محليين', 'توريد مستمر', 'أسعار الجملة', 'البيع المباشر', 'بيع بالجملة للمنتجات الإلكترونية', 'تخفيضات بالجملة', 'خدمات بيع بالجملة', 'استيراد بالجملة', 'التوريد بالجملة', 'تسوق بالجملة', 'طلبات بالجملة', 'مشتريات جملة', 'بيع بالجملة للمؤسسات', 'بيع بالجملة للمصانع', 'توزيع بالجملة', 'المنتجات بالجملة', 'بيع بالجملة للمنتجات الاستهلاكية', 'توريد بالجملة للعملاء', 'توفير بالجملة', 'بيع بالجملة للأعمال التجارية', 'أسعار الجملة المنخفضة', 'شحن بالجملة', 'منتجات بالجملة بأفضل الأسعار', 'توريد سريع', 'بيع بالجملة عبر الإنترنت', 'طلب بالجملة', 'تجارة الجملة المحلية'],
            'tags_en' => ['wholesale', 'bulk products', 'wholesale trade', 'bulk buying', 'low prices', 'bulk discounts', 'business purchases', 'local trade', 'wholesale buying', 'wholesale supply', 'bulk product selling', 'restaurant supplies', 'wholesalers', 'bulk orders', 'competitive bulk prices', 'wholesale for stores', 'wholesale for restaurants', 'wholesale for groceries', 'wholesale for hospitals', 'local suppliers', 'continuous supply', 'wholesale prices', 'direct selling', 'wholesale for electronics', 'bulk discounts', 'wholesale services', 'wholesale importing', 'wholesale supply', 'wholesale shopping', 'bulk purchases', 'wholesale requests', 'bulk buying', 'wholesale for institutions', 'wholesale for factories', 'wholesale distribution', 'bulk products', 'wholesale for consumer goods', 'wholesale supply for clients', 'bulk savings', 'wholesale business', 'low wholesale prices', 'wholesale shipping', 'bulk products at best prices', 'fast supply', 'wholesale online orders', 'bulk trade'],
        ]);
    }
}
